### ISSUE TITLE
Possible error in native search?

### ISSUE THREAD

**Issue by abylouw** [stbrumme/practical-string-searching#1]
Hi,

Thank you for this code. I have implemented the search in a string tokenizer that I wrote. But it seems that the line referenced below (in searchNative) might be wrong. 

https://github.com/stbrumme/practical-string-searching/blob/7338f8b42aaa43b32a2fc7b5679d2fa6cf57fc59/search.c#L546

If I test it as is then `haystackLength` get's too small too quickly, whilst if I just replace that line with:

`haystackLength = haystackEnd - haystack;`

then the algorithm makes sense to me and it works in my tests.

**Comment by stbrumme** [comment]
You are absolutely right !
I did a few performance tests and it turns out that merging the 2-bytes search into the general case doesn't slow down the algorithm at all - and reduces the code size.

Thanks for pointing out that bug - see https://github.com/stbrumme/practical-string-searching/commit/d168a81eb33b17aea2415e8c457e87552276ab5a
